import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

import Featured from '../components/ui/Featured'
import PoductList from "../components/ui/poductList"

export default function Home({productList}:{productList:any}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>blaaa</h1>
      <Featured/>
      <PoductList productList={productList}/>
      </main>
    </>
  )
}

export const getServerSideProps = async () => {
  // const res = await axios.get(`http://localhost:3000/api/products`);
  // console.log(res.data)
  const res = await fetch('http://localhost:3000/api/products');
  const data = await res.json();

  console.log(data);

  return {
    props: {
      productList : data,
    }
  }
}